[project]
site_name = "BorgBoi Docs"
copyright = "Copyright &copy; 2026 Zach Fuller"
site_url = "https://fullerzz.github.io/borgboi/"
repo_url = "https://github.com/fullerzz/borgboi"
repo_name = "fullerzz/borgboi"

nav = [
    { "Overview" = "index.md" },
    { "Getting Started" = "pages/getting-started.md" },
    { "Commands" = "pages/commands.md" },
    { "User Configuration" = "pages/user-configuration.md" },
    { "SQLite Database" = "pages/sqlite-database.md" },
]

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/fullerzz/borgboi"

[project.theme]
variant = "modern"
favicon = "images/favicon.ico"
features = [
    "navigation.instant",
    "navigation.instant.progress",
    "navigation.tracking",
    "navigation.expand",
    "navigation.path",
    "navigation.top",
    "toc.follow",
]

[project.theme.icon]
logo = "fontawesome/solid/hard-drive"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "material/brightness-auto"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "teal"
accent = "pink"
toggle.icon = "material/toggle-switch"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "black"
accent = "deep orange"
toggle.icon = "material/toggle-switch-off-outline"
toggle.name = "Switch to light mode"

[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
    { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" },
]

[project.markdown_extensions.pymdownx.details]

[project.markdown_extensions.pymdownx.blocks.caption]

[project.markdown_extensions.admonition]

[project.markdown_extensions.attr_list]

[project.markdown_extensions.md_in_html]

[project.markdown_extensions.tables]

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
use_pygments = true
pygments_lang_class = true

[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.markdown_extensions.toc]
permalink = true

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
