name: uv Lockfile Report

on:
  pull_request:
    paths:
      - "uv.lock"

permissions:
  contents: read
  pull-requests: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0

      - name: Report
        uses: mw-root/uv-lock-report@dc61e2c8bceda25c9008d60b8bcda2dea8ab5aef # v0.14.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
